// <auto-generated />
using System;
using Leitweb.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leitweb.Api.Data.Migrations
{
    [DbContext(typeof(LeitwebDbContext))]
    [Migration("20260829192937_SyncGisModelSnapshot")]
    partial class SyncGisModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "case_status", new[] { "open", "under_investigation", "submitted", "closed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "dispatch_status", new[] { "draft", "dispatched", "acknowledged", "returned" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "document_type", new[] { "short_report", "criminal_complaint", "incident_report", "witness_statement", "seizure_record", "cover_letter", "closing_report", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "evidence_status", new[] { "seized", "secured", "in_storage", "sent_for_examination", "released", "destroyed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "incident_status", new[] { "open", "dispatched", "in_progress", "closed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "person_role", new[] { "accused", "suspect", "victim", "witness", "reporting_person", "injured_person", "guardian", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "police_occasion", new[] { "other", "traffic_accident", "disturbance", "theft", "burglary", "assault", "domestic_violence", "missing_person", "suspicious_person", "property_damage", "traffic_control", "administrative_assistance" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "resource_status", new[] { "unavailable", "available", "dispatched", "on_scene" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leitweb.Api.Domain.AddressEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Street");

                    b.HasIndex("Municipality", "Street", "HouseNumber")
                        .IsUnique();

                    b.ToTable("address_register", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.CaseDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PoliceCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoliceCaseId");

                    b.ToTable("case_documents", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.CasePerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PoliceCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoliceCaseId");

                    b.ToTable("case_persons", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.DocumentDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DispatchedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseDocumentId");

                    b.ToTable("document_dispatches", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("PoliceCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SecuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecuredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PoliceCaseId", "EvidenceNumber")
                        .IsUnique();

                    b.ToTable("evidence_items", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.GisFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,4326)");

                    b.Property<Guid>("GisLayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("GisLayerId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("gis_features", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.GisLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("gis_layers", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.GisMapProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "UserSubject", "Name")
                        .IsUnique();

                    b.ToTable("gis_map_profiles", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.GisSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LayerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ServiceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("gis_sources", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Occasion")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ReferenceNumber")
                        .IsUnique();

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.IncidentResource", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IncidentId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("incident_resources", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.IncidentStatusEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("incident_status_history", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.OperationalResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallSign")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CallSign")
                        .IsUnique();

                    b.ToTable("operational_resources", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.PoliceCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "FileNumber")
                        .IsUnique();

                    b.ToTable("police_cases", (string)null);
                });

            modelBuilder.Entity("Leitweb.Api.Domain.CaseDocument", b =>
                {
                    b.HasOne("Leitweb.Api.Domain.PoliceCase", "PoliceCase")
                        .WithMany("Documents")
                        .HasForeignKey("PoliceCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliceCase");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.CasePerson", b =>
                {
                    b.HasOne("Leitweb.Api.Domain.PoliceCase", "PoliceCase")
                        .WithMany("Persons")
                        .HasForeignKey("PoliceCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliceCase");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.DocumentDispatch", b =>
                {
                    b.HasOne("Leitweb.Api.Domain.CaseDocument", "Document")
                        .WithMany("Dispatches")
                        .HasForeignKey("CaseDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.EvidenceItem", b =>
                {
                    b.HasOne("Leitweb.Api.Domain.PoliceCase", "PoliceCase")
                        .WithMany("EvidenceItems")
                        .HasForeignKey("PoliceCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliceCase");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.GisFeature", b =>
                {
                    b.HasOne("Leitweb.Api.Domain.GisLayer", "Layer")
                        .WithMany("Features")
                        .HasForeignKey("GisLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.IncidentResource", b =>
                {
                    b.HasOne("Leitweb.Api.Domain.Incident", "Incident")
                        .WithMany("AssignedResources")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leitweb.Api.Domain.OperationalResource", "Resource")
                        .WithMany("Incidents")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.IncidentStatusEntry", b =>
                {
                    b.HasOne("Leitweb.Api.Domain.Incident", "Incident")
                        .WithMany("StatusHistory")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.PoliceCase", b =>
                {
                    b.HasOne("Leitweb.Api.Domain.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.CaseDocument", b =>
                {
                    b.Navigation("Dispatches");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.GisLayer", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.Incident", b =>
                {
                    b.Navigation("AssignedResources");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.OperationalResource", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Leitweb.Api.Domain.PoliceCase", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("EvidenceItems");

                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
